[package]
name = "cu-logging-size"
description = "This is an example for the Copper project to show how to set custom logging parameters."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

publish = false
[dependencies]
cu29 = { workspace = true }
cu29-helpers = { workspace = true }
tempfile = { workspace = true }
serde = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["serde"]
