[package]
name = "cargo-cubuild"
description = "A cargo tool to help with copper macro expansion errors."
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/copper-project/copper-rs"

[dependencies]
[workspace]
