[package]
name = "cu29-derive"
description = "This is the copper project runtime generator. It cannot be used independently from the copper project."
documentation = "https://docs.rs/cu29-derive"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
cu29-runtime = { workspace = true, features = ["std"] }
cu29-traits = { workspace = true }
convert_case = "0.11"
itertools = { version = "0.14", default-features = false }
quote = { workspace = true }
proc-macro2 = { workspace = true }
syn = { workspace = true }
walkdir = "2.5"

[build-dependencies]
cu29-unifiedlog = { workspace = true } # needed

[dev-dependencies]
trybuild = "1.0"
rustc_version = "0.4"
cu29 = { workspace = true }  # needed for compile_fail tests
serde = { workspace = true } # needed for compile_fail tests

[features]
default = ["std"]
# enables a more verbose build log showing the code generation.
macro_debug = ["cu29-runtime/macro_debug"]
logviz = []
std = ["cu29-traits/std", "cu29-unifiedlog/std"]
rtsan = []

[package.metadata.cargo-shear]
ignored-paths = ["tests/compile_fail/**.rs"]
