[package]
name = "cu-caterpillar"
default-run = "cu-caterpillar"
description = "This is an example for the Copper project to measure a base latency from the runtime. It can be used dry running on a host or on a Raspberry Pi flipping GPIO pins."

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[package.metadata.cargo-machete]
ignored = ["cu29-log", "cu29-log-runtime", "cu29-unifiedlog", "copper-traits"]  # proc macro

[[bin]]
name = "cu-caterpillar"
path = "src/main.rs"

[[bin]]
name = "cu-caterpillar-logreader"
path = "src/logreader.rs"


[dependencies]
cu29-prelude = { workspace = true }
cu29-export = { workspace = true }
cu-consolemon = { path = "../../components/monitors/cu_consolemon", version = "0.5.1" }  # needed
compact_str = { workspace = true }  # needed
cu-rp-gpio = { path = "../../components/sinks/cu_rp_gpio", version = "0.5.1" }
tempfile = "3.14.0"


[features]
default = ["mock"]
mock = ["cu-rp-gpio/mock"]
