[package]
name = "cu-caterpillar"
default-run = "cu-caterpillar"
description = "This is an example for the Copper project to measure a base latency from the runtime. It can be used dry running on a host or on a Raspberry Pi flipping GPIO pins."

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[package.metadata.cargo-machete]
ignored = [
    "cu29-log",
    "cu29-log-runtime",
    "cu29-unifiedlog",
    "cu-consolemon",
    "copper-traits",
] # proc macro and console

[[bin]]
name = "cu-caterpillar"
path = "src/main.rs"

[[bin]]
name = "cu-caterpillar-logreader"
path = "src/logreader.rs"


[dependencies]
cu29 = { workspace = true, features = ["macro_debug"]}
cu29-helpers = { workspace = true }
cu29-export = { workspace = true, features = ["python"] }
bincode = { workspace = true }
# cu-consolemon = { path = "../../components/monitors/cu_consolemon", default-features = false, version = "0.6" }  # needed
cu-consolemon = { path = "../../components/monitors/cu_consolemon", version = "0.8.0" } # needed
cu-rp-gpio = { path = "../../components/sinks/cu_rp_gpio", version = "0.8.0" }
tempfile = { workspace = true }


[features]
default = ["mock"]
mock = ["cu-rp-gpio/mock"]
