[package]
name = "cu-missions"
description = "This shows how to build a multimission configuration and switch from one mission to another."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true


publish = false
[dependencies]
cu29 = { workspace = true }
cu29-helpers = { workspace = true }
tempfile = { workspace = true }
serde = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["serde"]
