[package]
name = "cu-iceoryx2-sink"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Copper sink task for Iceoryx2."

[dependencies]
iceoryx2 = { version = "0.6.1" }
cu29 = { workspace = true }
bincode = { workspace = true }
