[package]
name = "cu-gnss-ublox-demo"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
cu29 = { workspace = true, features = ["log-level-debug"] }
cu29-helpers = { workspace = true }
cu-gnss-ublox = { path = "../../components/sources/cu_gnss_ublox", version = "0.13.0" }
cu-gnss-payloads = { workspace = true }
cu29-export = { workspace = true, optional = true }
cu-linux-resources = { workspace = true }
tempfile = { workspace = true }
serde = { workspace = true }
ctrlc = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["serde", "cu-linux-resources"]

[features]
default = []
logexport = ["dep:cu29-export", "cu-gnss-ublox/reflect"]
