[package]
name = "cu29-clock"
description = "Copper Robot Clock implementation. It is a monotonic high precision clock for real time applications. It has a mock feature for testing time dependent behaviors. It is part of the Copper project but can be used independently."
documentation = "https://docs.rs/cu29-clock"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
bincode = { workspace = true }
serde = { workspace = true }
bevy_reflect = { workspace = true, optional = true }
portable-atomic = { version = "1.11", default-features = false, features = [
  "fallback",
] }

[target.'cfg(all(target_arch = "arm", target_os = "none"))'.dependencies]
cortex-m = { workspace = true }

[dev-dependencies]
approx = { version = "0.5", default-features = false }

[features]
default = ["std"]
reflect = ["dep:bevy_reflect"]
std = ["portable-atomic/std", "portable-atomic/require-cas"]
