[package]
name = "cu-logmon"
description = "Lightweight Copper monitor that emits periodic stats over the standard Copper logging macros."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
build = "build.rs"

[lib]
path = "src/lib.rs"


[dependencies]
cu29 = { path = "../../../core/cu29", version = "0.11.0", default-features = false }
defmt = { version = "1.0", optional = true }
spin = { workspace = true }

[dev-dependencies]
log = "0.4"
cu29 = { path = "../../../core/cu29", version = "0.11.0", default-features = false, features = [
  "log-level-info",
] }
cu29-helpers = { path = "../../../core/cu29_helpers", version = "0.11.0" }
serde = { workspace = true }


[features]
default = ["std", "color_log"]
std = ["cu29/std"]
defmt = ["cu29/defmt", "dep:defmt"]
color_log = []
textlogs = ["cu29/textlogs"]
log-level-info = ["cu29/log-level-info"]
