[package]
name = "cu-logmon"
description = "Lightweight Copper monitor that emits periodic stats over the standard Copper logging macros."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
build = "build.rs"

[package.metadata.cargo-shear]
ignored = ["serde"]

[lib]
path = "src/lib.rs"


[dependencies]
cu29 = { path = "../../../core/cu29", version = "0.13.0", default-features = false }
cu29-log-runtime = { path = "../../../core/cu29_log_runtime", version = "0.13.0", default-features = false }
spin = { workspace = true }

[dev-dependencies]
log = { workspace = true }
cu29 = { path = "../../../core/cu29", version = "0.13.0", default-features = false, features = [
  "log-level-info",
] }
cu29-helpers = { path = "../../../core/cu29_helpers", version = "0.13.0" }
serde = { workspace = true }


[features]
default = ["std", "color_log"]
std = ["cu29/std", "cu29-log-runtime/std"]
defmt = ["cu29/defmt"]
color_log = []
textlogs = ["cu29/textlogs"]
log-level-info = ["cu29/log-level-info"]
