[package]
name = "cu29-traits"
description = "Common systems and robotics traits designed to decouple the components of your robotic system. These can be used independently from the Copper project."
documentation = "https://docs.rs/cu29-traits"
readme = "README.md"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
cu29-clock = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }
compact_str = { workspace = true }
erased-serde = { workspace = true }
defmt = { workspace = true, optional = true, default-features = false, features = [
  "alloc",
] }

[features]
default = ["std"]
std = ["cu29-clock/std", "compact_str/std", "serde/std"]
defmt = ["dep:defmt"]                                    # this is only used for baremetal text logging

[dev-dependencies]
serde_json = "1.0"
