[package]
name = "cu-basic-fc"
description = "This is a basic quadcopter Flight Controller implemented end to end using Copper components"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
# default-run = "quad-sim"

[dependencies]
cu29 = { workspace = true }
cu29-helpers = { workspace = true }
cu-consolemon = { path = "../../components/monitors/cu_consolemon", version = "0.11.0" } # needed
cu-pid = { path = "../../components/tasks/cu_pid", version = "0.11.0" }

# Log reader depencies
cu29-export = { workspace = true, optional = true }

# Sim dependencies
bevy = { version = "0.16.0", default-features = false, features = ["x11", "wayland", "default_font", "bevy_render", "bevy_window", "bevy_core_pipeline", "bevy_pbr", "bevy_scene", "bevy_sprite", "bevy_gltf", "animation", "bevy_picking", "bevy_mesh_picking_backend", "tonemapping_luts", "bevy_ui", "ktx2", "jpeg", "png"], optional = true }
avian3d = { version = "0.3.0", default-features = false, features = ["bevy_scene", "collider-from-mesh", "debug-plugin", "parallel", "f32", "3d", "parry-f32"], optional = true }
cached-path = { version = "0.9.0", optional = true }
iyes_perf_ui = { version = "0.5.0", optional = true }

[features]
default = ["logreader", "sim"]
logreader = ["dep:cu29-export"]
sim = ["dep:bevy", "dep:avian3d", "dep:cached-path", "dep:cu29-export"]
perf-ui = ["dep:iyes_perf_ui"]

# [[bin]]
# name = "quad"
# path = "src/main.rs"

# [[bin]]
# name = "quad-logreader"
# path = "src/logreader.rs"
# required-features = ["logreader"]

# [[bin]]
# name = "quad-sim"
# path = "src/sim.rs"
# required-features = ["sim"]
# 
# [[bin]]
# name = "quad-resim"
# path = "src/resim.rs"
# required-features = ["sim"]
