[package]
name = "cu-standalone-structlog"
description = "Example of using structlog in a standalone application"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "structlog_perf"
path = "src/structlog_perf.rs"

[[bin]]
name = "standardlog_perf"
path = "src/standardlog_perf.rs"

[dependencies]
cu29 = { workspace = true }  # needed
cu29-clock = { workspace = true }
log = "0.4.27"
simplelog = "0.12.2"
