[package]
name = "cu-gstreamer"
description = "This is a Copper GStreamer sink."

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
cu29 = { workspace = true }
bincode = { workspace = true }
circular-buffer = { workspace = true }
gstreamer = { workspace = true, default-features = false, optional = true }
gstreamer-app = { version = "0.24", default-features = false, optional = true }
serde = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
rerun = { workspace = true }
cu29-helpers = { workspace = true }

[build-dependencies]
cfg_aliases = { workspace = true }

[features]
gst = ["dep:gstreamer", "dep:gstreamer-app"]
