[package]
name = "cu-lewansoul"
description = "This is a driver for the Lewansoul serial servos."

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
uom = { workspace = true }
cu29 = { workspace = true }
bincode = { workspace = true }
serialport = "4.5.1"
log = "0.4.22"
