[package]
name = "cu-zenoh-sink"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Copper sink task for Zenoh."

[dependencies]
zenoh = { version = "1.7.0", default-features = false, features = [
  "transport_tcp",
] }
cu29 = { workspace = true }
