[package]
name = "cu29-log"
description = "This is part of the text logging runtime for Copper. It cannot be used independently from the copper project."
documentation = "https://docs.rs/cu29-log"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
bincode = { workspace = true }
serde = { workspace = true }
cu29-value = { workspace = true }
cu29-traits = { workspace = true }
cu29-clock = { workspace = true }
strfmt = { workspace = true, optional = true } # strfmt is std only
smallvec = { workspace = true }
defmt = { workspace = true, optional = true }

[features]
default = ["std"]
std = ["cu29-clock/std", "cu29-traits/std", "cu29-value/std", "dep:strfmt"]
defmt = ["dep:defmt"]                                                       # this is only used for baremetal text logging
