[package]
name = "cu-ros2-payloads"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
description = "ROS2 Payloads that can be constructed from/to Copper Payloads for compatibility"

[dependencies]
compact_str = { workspace = true }
serde = { workspace = true }
cu-sensor-payloads = { workspace = true }
cu29 = { workspace = true }

[features]
humble = [] # Activate for ROS2 Humble, disable for later versions

[dev-dependencies]
cdr = { version = "0.2.4" }
