[package]
name = "cu-gnss-payloads"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Standardized GNSS payload definitions for Copper"

[dependencies]
bincode = { workspace = true }
cu29 = { path = "../../../core/cu29", version = "0.12.0", default-features = false }
serde = { workspace = true }
uom = { version = "0.37", default-features = false, features = [
  "serde",
  "f32",
  "si",
  "autoconvert",
] }

[features]
default = ["std"]
std = ["cu29/std"]
textlogs = ["cu29/textlogs"]
