[package]
name = "cu-multisources-structs"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Schema-only example showing how to define multiple Copper data sources"
default-run = "sim-test"

publish = false
[[bin]]
name = "sim-test"
path = "src/main.rs"

[[bin]]
name = "sim-test-logreader"
path = "src/logreader.rs"
required-features = ["logreader"]

[features]
default = []
logreader = ["dep:cu29-export"]

[dependencies]
cu29 = { workspace=true, features = ["macro_debug"] }
bincode = { workspace=true, features = ["derive"] }
serde = { workspace=true, features = ["derive"] }
cu29-helpers = { workspace=true  }
cu29-export = { workspace=true, optional = true }
