[package]
name = "cu-hesai"
description = "Copper driver for Hesai X32. Note: the actual parsing is usable outside of Copper if you need a Hesai X32 driver for another project."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
cu29-clock = { workspace = true }
cu29-log = { workspace = true }
cu29-log-derive = { workspace = true }
cu29-log-runtime = { workspace = true }
cu-sensor-payloads = { workspace = true }

pcap = "*"
bytemuck = { version = "1.18.0", features = ["derive"] }
uom = { workspace = true }
chrono = { version = "0.4.38" }
cu29 = { workspace = true }
socket2 = { version = "0.5.7", features = ["all"] }
sysctl = "0.6"
