[package]
name = "cu-hesai"
description = "Copper driver for Hesai X32. Note: the actual parsing is usable outside of Copper if you need a Hesai X32 driver for another project."
readme = "README.md"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
cu29 = { workspace = true }
cu-sensor-payloads = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
chrono = { workspace = true, features = ["serde"] }
socket2 = { workspace = true, features = ["all"] }
bincode = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
cu-udp-inject = { path = "../../testing/cu_udp_inject", version = "0.13.0" }
cu29-helpers = { workspace = true }
serde = { workspace = true }

[features]
hardware = []
