[package]
name = "cu-min-baremetal"
default-run = "cu-min-baremetal"
description = "This is a minimal example/smoke test of a baremetal (no_std) application using cu29."

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

publish = false
[package.metadata.copper]
embedded_only = true
embedded_config = "examples/cu_min_baremetal/.cargo/config-nostd.toml"
embedded_target = "aarch64-unknown-none"
embedded_no_default_features = true

[[bin]]
name = "cu-min-baremetal"
path = "src/main.rs"

[[bin]]
name = "cu-min-baremetal-logreader"
path = "src/logreader.rs"
required-features = ["std"]

[dependencies]

bincode = { workspace = true }
# cu29 = { path = "../../core/cu29", default-features = false, features = ["macro_debug"] }  # needed for cargo-cubuild
cu29 = { path = "../../core/cu29", default-features = false, version="0.10.0" }  # default-features = false -> enables no-std for all cu29 dependencies
cu29-helpers = { workspace = true, optional = true } # std only
serde = { workspace = true }
spin = { workspace = true }
embedded-alloc = "0.6"

# host only
cu29-export = { workspace = true, features = ["python"], optional = true }

[features]
default = ["std"]   # Compile with --no-default-features to target no_std
std = [
    "dep:cu29-helpers",
    "dep:cu29-export",
    "bincode/std",
    "serde/std",
]
