[package]
name = "cu-consolemon"
description = "A monitoring TUI for Copper. See the main Copper repository for more information."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
default = ["debug_pane"]
# Enables 'Debug Output' Pane
debug_pane = ["dep:log", "dep:chrono", "dep:dashmap"]

[dependencies]
cu29 = { workspace = true }
cu29-log-runtime = { workspace = true }
compact_str = { workspace = true }
ratatui = "0.29"
pfetch-logo-parser = "0.1"
pfetch = "2.11"
dotenvy = "0.15"
libmacchina = "7.3" # 8.0.0+ is not supported by pfetch at the time of writing
ansi-to-tui = "7.0"
tui-nodes = "0.8"
tui-widgets = "0.4"  # 0.4.0 brings ratatui 0.29
color-eyre = "0.6"
gag = "1.0.0"
log = { version = "0.4.25", features = ["std"], optional = true }
chrono = { version = "0.4.39", optional = true }
dashmap = { version = "6.1.0", optional = true }
