[package]
name = "cu-human-pose"
description = "Pose estimation demo using Candle and GStreamer camera input"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

publish = false

[features]
default = ["cpu"]
cpu = []
cuda = ["candle-core/cuda", "candle-nn/cuda"]

[dependencies]
cu29 = { workspace = true, features = ["log-level-info", "textlogs"] }
cu29-helpers = { workspace = true }
cu-gstreamer = { path = "../../components/sources/cu_gstreamer", version = "0.12.0", features = [
  "gst",
] }
cu-sensor-payloads = { path = "../../components/payloads/cu_sensor_payloads", version = "0.12.0" }
cu-consolemon = { path = "../../components/monitors/cu_consolemon", version = "0.12.0" }
gstreamer = { version = "0.24", default-features = false }

# Candle ML framework
# the current alpha version has a forced dependency conflict on curarc with ug
candle-core = { git = "https://github.com/huggingface/candle.git" }
# candle-core ="0.9.2-alpha.2"
candle-nn = { git = "https://github.com/huggingface/candle.git" }
# candle-nn ="0.9.2-alpha.2"
# candle-transformers = { git = "https://github.com/huggingface/candle.git"}
# Visualization
rerun = { workspace = true }

# Serialization
bincode = { workspace = true }
serde = { workspace = true }

# Model download
hf-hub = "0.4.3"

# Misc
tempfile = { workspace = true }
env_logger = "0.11"

[build-dependencies]
hf-hub = "0.4.3"
