[default.extend-words]
mis = "mis"
ratatui = "ratatui"
numer = "numer"
thr = "thr"
IST = "IST"
iterm = "iterm"
NED = "NED"
arange = "arange"
mmaped = "mmaped"

[files]
extend-exclude = ["patches/*", "components/payloads/cu_ros_payloads/**"]
