[advisories]
ignore = [
  "RUSTSEC-2024-0388", # derivative is unmaintained. https://rustsec.org/advisories/RUSTSEC-2024-0388.html
  "RUSTSEC-2024-0436", # paste is no longer maintaind. https://rustsec.org/advisories/RUSTSEC-2024-0436.html
  "RUSTSEC-2025-0119", # number_prefix is no longer actively maintained. https://rustsec.org/advisories/RUSTSEC-2025-0119
  "RUSTSEC-2025-0141", # bincode is no longer maintained. https://rustsec.org/advisories/RUSTSEC-2025-0141
]
