[package]
name = "cu-config-variation"
description = "Example of a Copper configuration with programmatic multiple variations"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

publish = false
[dependencies]
cu29 = { workspace = true }
cu29-helpers = { workspace = true }
cu-caterpillar = { path = "../cu_caterpillar", version = "0.12.0" }
cu-rp-gpio = { path = "../../components/sinks/cu_rp_gpio", version = "0.13.0" }
serde = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["cu-caterpillar", "cu-rp-gpio", "serde"]
