[package]
name = "cu-iceoryx2-src"
description = "Copper source task for Iceoryx2. I allows Copper to receive messages from Iceoryx2."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
iceoryx2 = { version = "0.4.1" }
iceoryx2-bb-log = { version = "0.4.1" }
cu29 = { workspace = true }
cu29-traits = { workspace = true }
cu29-derive = { workspace = true }
cu29-log-derive = { workspace = true }
cu29-log = { workspace = true }
cu29-log-runtime = { workspace = true }
cu29-helpers = { workspace = true }
cu29-unifiedlog = { workspace = true }
cu29-export = { workspace = true }
bincode = { workspace = true }
