[package]
name = "cu-zenoh-bridge"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Copper bridge for bidirectional Zenoh messaging."

[dependencies]
zenoh = { workspace = true, default-features = false, features = [
  "transport_tcp",
] }
cu29 = { workspace = true }
serde = { workspace = true }
serde_json = { version = "1.0", default-features = false }
minicbor-serde = { workspace = true, default-features = false, features = [
  "alloc",
] }
bincode = { workspace = true }
