[package]
name = "cu-zenoh-bridge"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Copper bridge for bidirectional Zenoh messaging."

[dependencies]
zenoh = { version = "1.4.0" }
cu29 = { workspace = true }
serde = { workspace = true }
serde_json = "1.0"
serde_cbor = "0.11"
bincode = { workspace = true }
