[package]
name = "cu-iceoryx2-bridge"
description = "Copper bridge for Iceoryx2 publish/subscribe services."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
cu29 = { path = "../../../core/cu29", version = "0.13.0", default-features = false }
iceoryx2 = { version = "0.8.0", default-features = false }
bincode = { workspace = true }

[features]
default = ["std"]
std = ["cu29/std", "iceoryx2/std"]
textlogs = ["cu29/textlogs"]
log-level-info = ["cu29/log-level-info"]
log-level-debug = ["cu29/log-level-debug"]
log-level-warning = ["cu29/log-level-warning"]
log-level-error = ["cu29/log-level-error"]
log-level-critical = ["cu29/log-level-critical"]
