[package]
name = "cu-iceoryx2"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Copper example to use Iceoryx2 as a middleware."

[dependencies]
iceoryx2 = { version = "0.4.1" }
iceoryx2-bb-log = { version = "0.4.1" }
cu29 = { workspace = true }
cu29-traits = { workspace = true }
cu29-derive = { workspace = true }
cu29-log-derive = { workspace = true }
cu29-log = { workspace = true }
cu29-log-runtime = { workspace = true }
cu29-helpers = { workspace = true }
cu29-unifiedlog = { workspace = true }
cu29-export = { workspace = true }
bincode = { workspace = true }
compact_str = { workspace = true }
cu-consolemon = { path = "../../components/monitors/cu_consolemon", version = "0.4.0" }
cu-rp-gpio = { path = "../../components/sinks/cu_rp_gpio", version = "0.4.0" }
cu-caterpillar = { path = "../cu_caterpillar", version = "0.4.0" }
cu-iceoryx2-sink = { path = "../../components/sinks/cu_iceoryx2_sink", version = "0.4.0" }
cu-iceoryx2-src = { path = "../../components/sources/cu_iceoryx2_src", version = "0.4.0" }
