[package]
name = "cu-image-aligner"
description = "Example showing image alignment using cu-aligner with pooled buffers."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
default-run = "cu-image-aligner"

publish = false

[dependencies]
cu29 = { workspace = true }
cu29-helpers = { workspace = true }
cu29-clock = { workspace = true }
tempfile = { workspace = true }
cu-aligner = { path = "../../components/tasks/cu_aligner", version = "0.12.0" }
cu-sensor-payloads = { path = "../../components/payloads/cu_sensor_payloads", version = "0.12.0" }
paste = { workspace = true }
serde = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["cu29-clock", "paste", "serde"]
