[package]
name = "cu29"
description = "Copper Runtime prelude crate. Copper is a Rust engine for robotics."
documentation = "https://docs.rs/cu29"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
cu29-clock = { workspace = true }
cu29-derive = { workspace = true }
cu29-log = { workspace = true }
cu29-log-derive = { workspace = true }
cu29-log-runtime = { workspace = true }
cu29-runtime = { workspace = true }
cu29-traits = { workspace = true }
cu29-units = { path = "../cu29_units", version = "0.13.0", default-features = false, optional = true }
cu29-unifiedlog = { workspace = true }
cu29-value = { workspace = true }
defmt = { workspace = true, optional = true }
rtsan-standalone = { workspace = true, optional = true }

bincode = { workspace = true }
serde = { workspace = true }

# only std
rayon = { workspace = true, optional = true }
ctrlc = { workspace = true, optional = true }

[features]
default = ["std", "textlogs", "units"]
defmt = [
  "dep:defmt",
  "cu29-log/defmt",
  "cu29-log-derive/defmt",
  "cu29-runtime/defmt",
  "cu29-traits/defmt",
] # for baremetal text logging
textlogs = ["cu29-log-derive/textlogs"]
units = ["dep:cu29-units"]
macro_debug = ["cu29-derive/macro_debug", "cu29-log-derive/macro_debug"]
logviz = ["cu29-derive/logviz"]
log-level-debug = ["cu29-log-derive/log-level-debug"]
log-level-info = ["cu29-log-derive/log-level-info"]
log-level-warning = ["cu29-log-derive/log-level-warning"]
log-level-error = ["cu29-log-derive/log-level-error"]
log-level-critical = ["cu29-log-derive/log-level-critical"]
reflect = ["cu29-clock/reflect", "cu29-runtime/reflect", "cu29-units?/reflect"]
remote-debug = ["cu29-runtime/remote-debug"]
std = [
  "rayon",
  "ctrlc",
  "cu29-clock/std",
  "cu29-derive/std",
  "cu29-log-derive/std",
  "cu29-log/std",
  "cu29-log-runtime/std",
  "cu29-runtime/std",
  "cu29-traits/std",
  "cu29-units?/std",
  "cu29-unifiedlog/std",
  "cu29-value/std",
]
rtsan = ["dep:rtsan-standalone", "cu29-derive/rtsan"]
