[package]
name = "cu29-log-runtime"
description = "This is part the runtime part of the text logger for Copper. It cannot be used independently from the Copper project."
documentation = "https://docs.rs/cu29-log-runtime"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
cu29-log = { workspace = true }
cu29-traits = { workspace = true }
cu29-clock = { workspace = true }
bincode = { workspace = true }
smallvec = { workspace = true }
spin = { workspace = true }
log = { workspace = true, default-features = false }
strfmt = { workspace = true, optional = true }

[dev-dependencies]
cu29-value = { workspace = true }

[features]
default = ["std"]
std = [
  "cu29-log/std",
  "cu29-traits/std",
  "cu29-clock/std",
  "bincode/std",
  "dep:strfmt",
]
