[package]
name = "cu-msp-bridge-loopback"
description = "An example application that demonstrates a loopback using the cu_msp_bridge component."
version.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "cu-msp-bridge-loopback"
path = "src/main.rs"

[dependencies]
cu29 = { workspace = true }
cu29-helpers = { workspace = true }
cu-linux-resources = { workspace = true }
cu-msp-bridge = { path = "../../components/bridges/cu_msp_bridge", version = "0.13.0" }
cu-msp-lib = { path = "../../components/libs/cu_msp_lib", version = "0.13.0" }
cu-consolemon = { path = "../../components/monitors/cu_consolemon", version = "0.13.0" }
nix = { workspace = true, default-features = false, features = ["term", "fs"] }
serde = { workspace = true }
ctrlc = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["serde", "cu-linux-resources"]
