[package]
name = "cu-msp-bridge-loopback"
description = "An example application that demonstrates a loopback using the cu_msp_bridge component."
version.workspace = true
edition.workspace = true
publish = false

[[bin]]
name = "cu-msp-bridge-loopback"
path = "src/main.rs"

[dependencies]
cu29 = { workspace = true }
cu29-helpers = { workspace = true }
cu29-unifiedlog = { workspace = true }
cu-msp-bridge = { path = "../../components/bridges/cu_msp_bridge", version = "0.10.0" }
cu-msp-lib = { path = "../../components/libs/cu_msp_lib", version = "0.10.0" }
cu-consolemon = { path = "../../components/monitors/cu_consolemon", version = "0.10.0" }
nix = { version = "0.29", features = ["term", "fs"] }
serde = { workspace = true }
ctrlc = "3"
