[package]
name = "cu-dynthreshold"
description = "Image Dynamic thresholding for Copper."

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
gstreamer = { workspace = true, default-features = false, optional = true }
cu29 = { workspace = true }
cu-sensor-payloads = { path = "../../payloads/cu_sensor_payloads", version = "0.13.0" }
cu-gstreamer = { path = "../../sources/cu_gstreamer", version = "0.13.0", optional = true }

[features]
# The 'gst' feature includes dependencies for GStreamer support.
# 'cu-gstreamer/gst' is included to propagate the 'gst' flag to the cu-gstreamer crate.
gst = ["dep:gstreamer", "dep:cu-gstreamer", "cu-gstreamer/gst"]
