[package]
name = "cu-sensor-payloads"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Those are standardized payloads for the Copper sensors. Feel free to contribute your own."

[dependencies]
bincode = { workspace = true }
cu29-soa-derive = { workspace = true }
cu29-clock = { workspace = true }
cu29 = { workspace = true }
uom = { workspace = true }
derive_more = { workspace = true }
image = { version="0.25.5", default-features=false }
bytemuck = "1.20.0"
# num_enum = "0.7.3"
