[package]
name = "cu-sensor-payloads"
readme = "README.md"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Those are standardized payloads for the Copper sensors. Feel free to contribute your own."

[dependencies]
bincode = { workspace = true }
cu29-soa-derive = { workspace = true }
cu29-clock = { path = "../../../core/cu29_clock", version = "0.13.0", default-features = false }
cu29 = { path = "../../../core/cu29", version = "0.13.0", default-features = false, features = [
  "units",
] }
rerun = { workspace = true, optional = true }
image = { workspace = true, default-features = false, optional = true }
kornia-image = { version = "0.1.10", optional = true }
serde = { workspace = true }

[features]
default = ["std"]
std = ["cu29/std", "cu29-clock/std"]
textlogs = ["cu29/textlogs"]
image = ["std", "dep:image"]
kornia = ["std", "dep:kornia-image"]
rerun = ["std", "dep:rerun"]
