[package]
name = "cu-bdshot"
description = "Copper Bridge to Bidirectional DSHOT ESCs."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
cu29 = { path = "../../../core/cu29", default-features = false }
rp235x-hal = { version = "0.3", features = ["critical-section-impl"] }
embedded-hal = "*"
pio = "=0.2.1"
pio-proc = "=0.2.1"
fugit = "*"
nb = "1"
cortex-m = "0.7.7"
critical-section = "1.1"
serde = { workspace = true, default-features = false, features = ["derive"] }
bincode = { workspace = true }
log = "0.4.28"
spin = { workspace = true }

[features]
default = []
defmt = []

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
panic = "abort"

[profile.dev]
panic = "abort"
