[package]
name = "cu-bdshot"
description = "Copper Bridge to Bidirectional DSHOT ESCs."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[package.metadata.copper]
embedded_only = true
embedded_target = "thumbv8m.main-none-eabihf"
embedded_features = "rp2350"

[dependencies]
cu29 = { path = "../../../core/cu29", version = "0.13.0", default-features = false }
rp235x-hal = { workspace = true, features = [
  "critical-section-impl",
], optional = true }
pio = { version = "0.3", optional = true }
stm32h7xx-hal = { workspace = true, default-features = false, features = [
  "stm32h743v",
], optional = true }
cortex-m = { workspace = true }
serde = { workspace = true, features = ["derive"] }
bincode = { workspace = true, features = ["alloc"] }
spin = { workspace = true }

[features]
default = ["messages-only"]
rp2350 = ["dep:rp235x-hal", "dep:pio"]
defmt = ["stm32h7xx-hal/defmt"]
stm32h7 = ["dep:stm32h7xx-hal", "defmt"]
messages-only = []
textlogs = ["cu29/textlogs"]
