[package]
name = "cu-bdshot"
description = "Copper Bridge to Bidirectional DSHOT ESCs."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[package.metadata.copper]
embedded_only = true
embedded_target = "thumbv8m.main-none-eabihf"

[dependencies]
cu29 = { path = "../../../core/cu29", default-features = false }
rp235x-hal = { version = "0.3", features = ["critical-section-impl"] }
embedded-hal = "*"
pio = "=0.2.1"
pio-proc = "=0.2.1"
fugit = "0.3.9"
nb = "1"
cortex-m = "0.7.7"
critical-section = "1.1"
serde = { workspace = true, default-features = false, features = ["derive"] }
bincode = { workspace = true, default-features = false, features = ["alloc"] }
log = "0.4.28"
spin = { workspace = true }
defmt = "1.0.1"

[features]
default = []
