[package]
name = "cu-bdshot"
description = "Copper Bridge to Bidirectional DSHOT ESCs."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[package.metadata.copper]
embedded_only = true
embedded_target = "thumbv8m.main-none-eabihf"
embedded_features = "rp2350"

[dependencies]
cu29 = { path = "../../../core/cu29", version="0.11.0", default-features = false }
rp235x-hal = { version = "0.3", features = ["critical-section-impl"], optional = true }
pio = { version = "=0.2.1", optional = true }  # Needed
pio-proc = { version = "=0.2.1", optional = true }
stm32h7xx-hal = { version = "0.16.0", default-features = false, features = ["stm32h743v"], optional = true }
cortex-m = "0.7.7"
serde = { workspace = true, features = ["derive"] }
bincode = { workspace = true, features = ["alloc"] }
spin = { workspace = true }
defmt = { version = "1.0.1", optional = true }

[features]
default = []
rp2350 = ["dep:rp235x-hal", "dep:pio", "dep:pio-proc"]
stm32h7 = ["dep:stm32h7xx-hal"]
defmt = ["dep:defmt", "stm32h7xx-hal/defmt"]
