[package]
name = "cu-livox"
description = "Copper driver for Livox Tele15. Note: the actual parsing is usable outside of Copper if you need a Livox Tele15 driver for another project."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
cu29 = { workspace = true }
cu-sensor-payloads = { workspace = true }
bytemuck = { version = "1.23.0", features = ["derive"] }
uom = { workspace = true }
chrono = { version = "0.4.41", features = ["serde"] }
socket2 = { version = "0.6.0", features = ["all"] }
tempfile = { workspace = true }

[dev-dependencies]
cu-udp-inject = { path = "../../testing/cu_udp_inject", version = "0.11.0" }
cu29-derive = { workspace = true }
cu29-helpers = { workspace = true }
serde = { workspace = true }

