[package]
name = "cu-msp-bridge"
description = "Copper bridge to talk to MSP devices over serial."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
cu29 = { path = "../../../core/cu29", version = "0.12.0", default-features = false }
cu-msp-lib = { path = "../../libs/cu_msp_lib", version = "0.12.0", default-features = false, features = [
  "bincode",
] }
embedded-io = { version = "0.6.1", default-features = false }
heapless = { workspace = true }
bincode = { workspace = true, features = ["alloc"] }
serde = { workspace = true }
cu-linux-resources = { workspace = true, optional = true }

[features]
default = ["std"]
std = [
  "cu29/std",
  "cu-msp-lib/std",
  "embedded-io/std",
  "dep:cu-linux-resources",
]
defmt = ["embedded-io/defmt-03", "cu29/defmt"]
alloc = ["embedded-io/alloc"]
textlogs = ["cu29/textlogs"]
log-level-info = ["cu29/log-level-info"]
