[package]
name = "cu-msp-bridge"
description = "Copper bridge to talk to MSP devices over serial."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
cu29 = { path = "../../../core/cu29", version = "0.11.0", default-features = false }
cu-msp-lib = { path = "../../libs/cu_msp_lib", version = "0.11.0", default-features = false, features = ["bincode"] }
serialport = { version = "4.8.1", optional = true }
embedded-io = { version = "0.6.1", default-features = false }
embedded-io-adapters = { version = "0.6.1", optional = true }
smallvec = { workspace = true }
bincode = { workspace = true, features = ["alloc"] }
serde = { workspace = true }
spin = { workspace = true }

[features]
default = ["std"]
std = ["cu29/std", "cu-msp-lib/std", "embedded-io/std", "dep:embedded-io-adapters", "dep:serialport", "embedded-io-adapters/std"]
defmt = ["embedded-io/defmt-03", "cu29/defmt"]
alloc = ["embedded-io/alloc"]
log-level-debug = ["cu29/log-level-debug"]
log-level-info = ["cu29/log-level-info"]
log-level-warning = ["cu29/log-level-warning"]
log-level-error = ["cu29/log-level-error"]
log-level-critical = ["cu29/log-level-critical"]
textlogs = ["cu29/textlogs"]
