[package]
name = "cu-pid"
description = "A PID controller for the Copper project."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
default = ["std"]
std = ["cu29/std", "bincode/std", "serde/std"]
textlogs = ["cu29/textlogs"]

[dependencies]
cu29 = { path = "../../../core/cu29", version = "0.12.0", default-features = false }
bincode = { workspace = true }
serde = { workspace = true }
bevy_reflect = { workspace = true }
