name: Weekly Audit and Beta Test

on:
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_TARGET_DIR: ${{ github.workspace }}/target

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@beta
        with:
          components: clippy, rustfmt
      - name: Install audit
        run: cargo install cargo-deny
      - name: Run deny bans
        run: cargo deny check bans -c .config/deny.toml
      - name: Run deny sources
        run: cargo deny check sources -c .config/deny.toml
      - name: Run deny advisories
        run: cargo deny check advisories -c .config/deny.toml
      - name: Check formatting
        run: cargo +beta fmt --all -- --check

  Unit-Tests:
    name: Unit Tests
    uses: ./.github/workflows/reusable-unit-tests.yml
    with:
      toolchain: beta
      cargo_target_dir: ${{ github.workspace }}/target

  embedded:
    name: CI for embedded targets
    uses: ./.github/workflows/reusable-embedded.yml
    with:
      toolchain: beta
      cargo_target_dir: ${{ github.workspace }}/target
