[package]
name = "cu29-export"
description = "This is the library support to build log exports for the copper project. It cannot be used independently from the copper project."
documentation = "https://docs.rs/cu29-export"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

# This is a python binding
[lib]
name = "cu29_export"
crate-type = ["cdylib", "rlib"]

[dependencies]
cu29 = { workspace = true }
cu29-clock = { workspace = true }
cu29-intern-strs = { workspace = true }
clap = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }
num-format = "0.4"

# PyO3 is not supported for macOS at the moment, don't allow people to opt-in since it won't work
pyo3 = { version = "0.27", optional = true, features = ["extension-module"] }

serde_json = "1.0"

[dev-dependencies]
tempfile = { workspace = true }
fs_extra = "1.3"

[features]
default = []
python = ["dep:pyo3"]
mcap = ["dep:mcap", "dep:serde-reflection", "dep:erased-serde"]

[dependencies.mcap]
version = "0.24"
optional = true

[dependencies.serde-reflection]
version = "0.4"
optional = true

[dependencies.erased-serde]
version = "0.4"
optional = true
