[package]
name = "cu29-export"
description = "This is the library support to build log exports for the copper project. It cannot be used independently from the copper project."
documentation = "https://docs.rs/cu29-export"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

# This is a python binding
[lib]
name = "cu29_export"
crate-type = ["cdylib", "rlib"]

[dependencies]
cu29 = { workspace = true, features = ["reflect"] }
cu29-clock = { workspace = true }
cu29-intern-strs = { workspace = true }
clap = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }
num-format = "0.4"
indicatif = { version = "0.18", optional = true, default-features = false }

# PyO3 is not supported for macOS at the moment, don't allow people to opt-in since it won't work
pyo3 = { version = "0.28", optional = true, default-features = false, features = [
  "extension-module",
] }

serde_json = { version = "1.0", default-features = false }

mcap = { version = "0.24", optional = true, default-features = false }
erased-serde = { version = "0.4", optional = true, default-features = false }


[dev-dependencies]
tempfile = { workspace = true }
jsonschema = { version = "0.41", default-features = false }

[features]
default = []
python = ["dep:pyo3"]
mcap = ["dep:mcap", "dep:erased-serde", "dep:indicatif"]
